### ISSUE TITLE
Template Plugin.

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#102]
# Introduction

Version 0.6.4 of tracardi-dot-notation  has new class: DotTemplate. This class is a singleton and has method render.
Once you pass a template to this method in form of:

Example:

```
My name is: {{profile@traits.private.pii.name}}
```

It will return a string where the placeholder {{profile@traits.private.pii.name}} will be replaced with profile data traits.private.pii.name.

# Plugin

Plugin takes a template in configuration and returns a string with replaced placeholders.

**Comment by DawidekZagajnik** [comment]
@atompie check https://github.com/DawidekZagajnik/tracardi-template-plugin to review plugin
