### ISSUE TITLE
Plugin: Add purchases to elastic

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#106]
# Intro

There is a new index tracardi-profile-purchases. We nee a new plugin that can add new purchase to this index.
Every time it will be executed a new purchase will be added to this index.

# Configuration

This plugin does not need configuration. It will take the data from payload.

# Payload

```
{
"name": PRODUCT NAME
"price": PRICE
"quantity": 1
}
```

Additional data should be appended to the payload:

```
"source": {
"id": "SOURCE-ID"
},
"profile": {
"id": PROFILE-ID
}
```

# Output 

Output has 2 ports

TRUE: triggered when everything went ok. 
```
{
"name": PRODUCT NAME,
"price": PRICE,
"quantity": 1,
"source": {
"id": "SOURCE-ID"
},
"profile": {
"id": PROFILE-ID
}
}
```

ERROR: returns error from elastic.

**Comment by DawidekZagajnik** [comment]
check https://github.com/DawidekZagajnik/tracardi-purchase-adder to review plugin

**Comment by atompie** [comment]
Will not be done. More generic approach needed
