### ISSUE TITLE
Endpoint: Add new scheduled event

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#108]
# Description

POST `/event/schedule` endpoint that adds new scheduled event

This endpoints reads JSON form body in form of:

```
{
source: {
   id: "<source-id>"
},
event: {
  type: "event-type",
  "properties": {
     "prop1": 1
   }
},
schedule: {
   "type": "date|delta|interval",
   "time": "+1m|2021-01-01T10:10:00"
}
}
```

It saves event to tracardi-tasks

This task is required by:

* https://github.com/atompie/tracardi-gui/issues/31

**Comment by atompie** [comment]
@DawidekZagajnik If you have new descriptions please create new PR. I would like to release new version by the end of this week.

**Comment by DawidekZagajnik** [comment]
check PRs from https://github.com/DawidekZagajnik/tracardi-api/tree/add-scheduled-event-endpoint
and 
https://github.com/DawidekZagajnik/tracardi/tree/add-scheduled-event-endpoint
