### ISSUE TITLE
Plugin: regex match

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#122]
Plugin that use regex.match to return matched data.

# Configuration

```
{
"pattern": "<pattern>",
"text": "<text or path to text>"
"groups": ["group A", "group B"]
```

Text can be a dotted path to data in profile, session, etc.

# Output 

```
{
"group A": "<matched string>",
"group B": "<matched string>",
}
```

**Comment by patromi** [comment]
https://github.com/patromi/tracardi-regex-match/tree/master

**Comment by atompie** [comment]
@patromi Could you provide a documentation for this plugin?

**Comment by patromi** [comment]
@atompie https://github.com/patromi/tracardi-regex-match/blob/master/README.md done :)
