### ISSUE TITLE
Plugin: Run jupyter notebook

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#126]
# Intro

This plugin will connect to jupyter notebook server and run defined notebook. It will need a token to access jupyter notebook and a notebook name - I guess

Config example

```
{
  "source": {
     "id": "<resource-id>"
   },
   "notebook": "<notebook-name>"
```

There maybe more information needed.

Resource should use a api-token template it look like this:

```
{
  "token": "<token>"
}
```

# Documentation

You will need to get familiar with jupyter API.

* https://jupyterhub.readthedocs.io/en/stable/reference/rest.html

# Running jupyter in docker

* https://hub.docker.com/r/jupyter/minimal-notebook

```
docker run -p 8888:8888 jupyter/minimal-notebook
```

**Comment by atompie** [comment]
@bartdob Any progress on this?

**Comment by bartdob** [comment]
working on it

**Comment by atompie** [comment]
Will not be done.
