### ISSUE TITLE
Finish descriptions of settings in endpoint /settings

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#127]
Some settings does not have descriptions. If you need information paste the settings that need clarification.

All settings are in settings_endpoint instead of env_endpoint.

**Comment by DawidekZagajnik** [comment]
check PR from https://github.com/DawidekZagajnik/tracardi-api/tree/settings-descriptions-updates

**Comment by atompie** [comment]
> check PR from https://github.com/DawidekZagajnik/tracardi-api/tree/settings-descriptions-updates

There is nothing under PR. You probably confused your repo with Tracardi's. Please see if it is correct.
