### ISSUE TITLE
Add tags to events: New index tracard-event-tags

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#129]
# Intro

We need to tag events to group them into meaningful groups. That's why we need to add tags to events. Tags are optional. You can tag one event with many tags. 

# New index

Create new index tracardi-event-tags. It needs the following data:

* type - this is event type
* tags - list of tags

Place new mapping into mapping folder and refer it in app.service.storage.index.

Example of connected index
```
"event-tags":        Index(multi_index=False,  index="tracardi-event-tags",   mapping="mappings/event-tags-index.json", rel=None),
```

Then restart tracardi and new index should be created.

# When the task is done

The task is done when mapping is created and index is connected.

**Comment by DawidekZagajnik** [comment]
@atompie check https://github.com/DawidekZagajnik/tracardi/tree/event-tags-index-setup and https://github.com/DawidekZagajnik/tracardi-api/tree/event-tags-index-setup to check progress, no PR for now, I'm gonna PR when all tags-related tasks are done
