### ISSUE TITLE
Service that rewrites tags to events

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#135]
There is a tag index that holds information on tags that belong to certain event types. This service must read into memory the settings form tag index and add cache it.

Place service function in service folder. Use MemoryCache.
The service should take the event and return it with tags filled.

See the test to get how it works.
```
def test_memory_cache_ttl():
    mc = MemoryCache()

    mc['test'] = CacheItem(data={"a": 1}, ttl=2)
    assert 'test' in mc

    sleep(1)
    assert 'test' in mc
    assert mc['test'].data == {"a": 1}

    sleep(2)mc = MemoryCache()

    mc['test'] = CacheItem(data={"a": 1}, ttl=2)

    try:
        x = mc['test']
        assert False
    except ExpiredException:
        assert True

    assert 'test' not in mc
```

**Comment by DawidekZagajnik** [comment]
what should be the value of ttl in CacheItem? How do I define it? Does it depend on some setting or should I set it arbitrarily to some int like 2 or 3?

**Comment by DawidekZagajnik** [comment]
set new env var tracardi/config, class MemoryCacheConfig (tags_ttl) and add it to settings endpoint
