### ISSUE TITLE
Plug-in to fetch data from elestic search.

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#143]
This plugin would fetch data form elastic instance.

# Prerequisites
 
- [x] #179

# Configuration

```
{
  "resource" : {
    "id": "<elastic-resource-id>",
    "index": "<elastic-index>",
    "query": {
    }
  }
}
```

# Output

Elastic response.

# Aux info

* Use storage.driver
* If the response from elastic is bigger then 20 records raise an error.

**Comment by DawidekZagajnik** [comment]
I wanna take this one if it's not already taken

**Comment by atompie** [comment]
> I wanna take this one if it's not already taken

The resource is already done but the plugin is free.
