### ISSUE TITLE
Tracking script issues when loading via GTM

### ISSUE THREAD

**Issue by bceyssens** [Tracardi/tracardi#180]
The example tracking script cannot be used with GTM

- `const` has to be replaced with `var`
- listeners options is required? script fails without it

Example:

`var options = {
        listeners: {
        },
        tracker: {
            url: {
                script: '.../tracker',
                api: '...'
            },
            source: {
                id: "..."
            }
        }
    }`

**Comment by atompie** [comment]
@bceyssens Does replacing const with var fix the issue?

**Comment by bceyssens** [comment]
@atompie it does. The missing "listeners" option probably is a different issue.

**Comment by atompie** [comment]
Ok then I know what to do. Thanks for spotting this issue.

**Comment by atompie** [comment]
Fixed. Need docker implementation.
