### ISSUE TITLE
Profiles last visit issue

### ISSUE THREAD

**Issue by bceyssens** [Tracardi/tracardi#182]
In the overview of all profiles, the last visit time seems to be fixed to a certain date. Existing and new profiles all use the same timestamp, in my screenshot all 1447 of them:

![Schermafdruk van 2021-11-18 09-42-20](https://user-images.githubusercontent.com/7702573/142381425-0d2741ad-45b5-47bd-91ad-81bf268bafe5.png)

**Comment by atompie** [comment]
@bceyssens We know about this issue. It its connected with caching. Please refresh the base to see new values. The lastVisit should be null. It should be updated with a workflow.

**Comment by bceyssens** [comment]
@atompie you're referring to a different problem I also noticed. Here, the last visit timestamp for new profiles (for example of today) is always 2021-11-16.

**Comment by atompie** [comment]
Ok I will take a look at this.

**Comment by atompie** [comment]
@danjohnson77 I assigned this task to you as I think this can be related to the caching problem your are working on. When the version with react-window is finished could you please check if this error is gone, Thanks :)

**Comment by atompie** [comment]
React.memo was removed and it solved the problem for this release.

**Comment by atompie** [comment]
Ok thanks I will take a look at this
