### ISSUE TITLE
Plugin: Plugin that makes a JSON form payload

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#183]
Some services require to send JSON instead of an object. 

# Input

```
{
 "to_json": "<path-to-data>"
}
```

# Output

```
{
  "json": "<json-string>"
}
```

**Comment by patromi** [comment]
@atompie https://github.com/patromi/tracardi-json-from-payload

**Comment by atompie** [comment]
@patromi  I will review it soon. Thanks

**Comment by atompie** [comment]
@patromi Could you fill the README.mf file with documentation?
