### ISSUE TITLE
Data limit

### ISSUE THREAD

**Issue by bceyssens** [Tracardi/tracardi#185]
Today we hit a 10000 items limit on events and I couldn't find any documentation on this. I have a few questions:

- I assume the oldest ones are getting removed? 
- Are there also limits on other sorts of data (profiles, sessions, ...)?
- Can we modify the behaviour or change the limits?

**Comment by atompie** [comment]
@bceyssens This must be a limit in elastic. We do not impose any limits. Could you elaborate on how the limit is visible. 

* Can you add new event or are you getting errors? 
* Can you provide some screenshots?

We will work on this issue as soon we get more information.

**Comment by bceyssens** [comment]
@atompie you are correct! This could be a limit on the query to Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html.

This is what I'm seeing:
![Schermafdruk van 2021-11-19 15-39-42](https://user-images.githubusercontent.com/7702573/142640743-e57bffaa-3687-428d-99a7-ea6fa579bbb3.png)

**Comment by atompie** [comment]
@bceyssens Yes it's a query limit.￼tracardi is designed to hold millions of events so you can filter them selecting a time range or typing a condition in the upper input. ￼￼￼

**Comment by atompie** [comment]
@bceyssens I see You Store a lot of events in tracardi. if yo￼u find that there is some missing functionality you would like to use ￼you can always￼ propose a usecase in discussions in the repo. ￼
