### ISSUE TITLE
UsecCase: Collect user consent

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#197]
# Intro

Some resources need user consent to collect data. Consent is granted by sending a defined event that is connected to workflow that grants or denies consents via running a consent plugin.

# Schema

````
{
  "type_id": "<consent-type-id>"
  "revoke": "<date>"
}
````
* type_id - consent type id
* revoke is optional and depends on the consent type definition - date to revoke consent.

Consent is attached to profile (consent field)

# Prerequisites

- [x] https://github.com/Tracardi/tracardi/issues/196

# Tasks

- [x] #211
- [x] #210
- [x] #267
- [ ] #268

**Comment by DawidekZagajnik** [comment]
wanna take this, but i need you @atompie to add descriptions for sub-tasks
