### ISSUE TITLE
Quirky behavior on Create/Edit Rule page

### ISSUE THREAD

**Issue by danzaar** [Tracardi/tracardi#209]
I noticed a couple oddities when creating and editing Rules.
I'm not sure if you prefer separate tickets for these issues, but as they are minor and related to the same page, I decided to bundle them.

Edit Rule: Flow not applying
---------------------------------
When trying to edit an existing Rule and entering a new Flow, the new Flow is not being created (and thus not applied).
Note that in case the Flow is created first, and then applied from the drop-down to the Rule to be edited, it works as it should and the change is applied correctly.

Create Rule: 'empty value' error when fields are filled in correctly
----------------------------------------------------------------------
Error gets thrown even when all (required) field are filled in. 

![empty-value-error](https://user-images.githubusercontent.com/54250476/143216012-0abf6963-ebe2-4fab-8c9a-95ad0d5f8b95.png)

Does not persist when selecting an existing Flow instead of entering a new one.

# Task

- [x] #212

**Comment by atompie** [comment]
@danzaar Thank you for reporting this issue. We will review and correct it shortly. I have one question though. Are you using dockerized version of Tracardi?

**Comment by danzaar** [comment]
> @danzaar Thank you for reporting this issue. We will review and correct it shortly. I have one question though. Are you using dockerized version of Tracardi?

Yes, that is correct.

**Comment by atompie** [comment]
@danzaar We removed the possibility to add new workflow form the rule form. We also refactored all forms to make it more consistent. The change will be available in docker with a week.
