### ISSUE TITLE
Consent plug-in

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#211]
# Plugin

Plugin adds to profile consent property new consent as:

```
{
  "type_id": "<consent-type-id>"
  "revoke": "<date>"
}
```

Profile consent is a list of consents given by user. 

# Config

```
{
  consent ; {
    "type_id": {
        "revoke":  "<date>"
    },
   "type_id": {
        "revoke":  "<date>"
    }
  }, ...  
}
```

Consent can not be added if it is not defined in consent_type index. If consent is defined as revokable then the revoke data can be added otherwise revoke = None. 

Plugin will append the configured consents to profile consent. Duplicates are not allowed. Old values should be replaced by new one.

# Input and Output returns payload.

**Comment by DawidekZagajnik** [comment]
Please specify "duplicates". Do you mean duplicates in terms of type_id or whole object?

**Comment by atompie** [comment]
Type id. Well this meandry that we could store oś as object instead of nested object.

**Comment by atompie** [comment]
@DawidekZagajnik Please notice a change in the task description 

```
Consent can not be added if it is not defined in consent_type index. If consent is defined as revokable then the revoke data can be added otherwise revoke = None.
```
