### ISSUE TITLE
422 response code on track

### ISSUE THREAD

**Issue by bceyssens** [Tracardi/tracardi#215]
Hi @atompie,

We're receiving this error on an environment we're testing Tracardi on:

```
liliput.min.js:1 POST <URL>/track 422
liliput.min.js:1 [Tracker] Could not save event. Error: 1 document(s) failed to index. - Limit of total fields [1000] has been exceeded
```

The site loads a bunch of other tracking scripts: Google, Bing, Facebook, DoubleClick, ... Could the amount of cookies be causing this issue?

**Comment by atompie** [comment]
@bceyssens A quick solution is https://stackoverflow.com/questions/55372330/what-does-limit-of-total-fields-1000-in-index-has-been-exceeded-means-in

This is elastic limit.

Have solution for that but need more information. Where do you store the most information is it context in session?
Are evaluation Tracardi and are open to index changes. Or you have a lot of indexed data and are not willing to change that.

**Comment by atompie** [comment]
@bceyssens Some more questions. 

As I understood the data comes form session cookies. Am I right?

* Do you need this cookie data? Maybe a reference id to external system would solve the problem. Then you could fetch the data from the other system when necessary within workflow. 
* Is limiting the cookies send to Tracardi solve your problem?

**Comment by bceyssens** [comment]
@atompie, it's solved when I clear other local storage data. We do not have control over cookie and local storage data because it is added by external (tracking) scripts. Is it possible to use a whitelist on the Tracardi tracking context for cookies and local storage data, I don't think we need to fill elastic with this data.

**Comment by atompie** [comment]
@bceyssens Sure That what I was thinking of. I will implement an option to filter cookies form context. 

@bceyssens could you please join our Tracardi workspace where we will discuss tracardi development and issues: [Tracardi slack channel](https://join.slack.com/t/tracardi/shared_invite/zt-znlomuhd-fatn3qxuI7VO9sBlHk~NhA)

**Comment by atompie** [comment]
@bceyssens this issue solves the problem. https://github.com/Tracardi/tracardi/issues/232
