### ISSUE TITLE
Absence of ability to delete/remove action nodes

### ISSUE THREAD

**Issue by danzaar** [Tracardi/tracardi#219]
To my understanding, as of right now there is no way to delete an action node while creating or editing a flow; forcing the user to create a new flow when placing the wrong action on the grid and/or when an existing node is not needed anymore.

**Comment by atompie** [comment]
@danzaar Yes there is select a node and press delete. The same can be done with edges (connection between nodes). Select edge and press delete. With the version 0.6.0 the select can be tricky as edges are a bit thin. But it is solved in new version and will be available soon. 


Please confirm if it is what you need. Thanks.

**Comment by danzaar** [comment]
@atompie Thank you for clarifying. Stupidly, I did not try the delete key. Naturally I tried looking for a Delete button and pressing Backspace, which I didn't find and did nothing. A right click option also did not exist.

Glad there is an option to delete nodes through the delete key, thanks!
