### ISSUE TITLE
Process data on cron

### ISSUE THREAD

**Issue by bceyssens** [Tracardi/tracardi#221]
Hi @atompie,

We would like to process all profile data on a specific time a day, like cron. What's the best way to do this?

This is needed when measuring profile interests. We use the key counter action to increase certain parts of the profile interests:

```
{
  "The Simpsons": 7,
  "Star Wars": 20
}
```

But interests can change over time so we need to decrease the accumulated values over time, for example with this calculation: ![half-life2](https://user-images.githubusercontent.com/7702573/143835651-b10d75d7-a8ad-4607-89cf-75ea09574962.png)

This is a simple calculation but it could be more complex in some cases. I don't know if it can be integrated in Tracardi.

**Comment by atompie** [comment]
@bceyssens Tell me if I understand it right. When the event comes you count some interests and save it in profile:

```
{
  "The Simpsons": 7,
  "Star Wars": 20
}
```

Then you want it to degrade over time?

If this is the case then your approach with cron is not very efficient. Although there is a possibility to schedule tasks in Tracardi is is not available in the community version, and it if not the approach you would like. I will not scale and will make unnecessary calls to tracardi just to decrease the interests. If you have like millions of profiles then it will slow the system. 

I see several approaches to solve your needs.

One is that you save interest as you do it now. And on the client side you calculate the drop in value of the profile interest (the insert time is available in profile so you can calculate the passed time). Pros - it is simple solution, Cons - you will not be able to search the entire index for profiles that has low - degraded interest. Only query single profile will get you a drop in interest metric. Though, you could query profile based on time and calculate the drop in interest metric for every record. 

Second approach it to use [Runtime field in elastic](https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime.html). They are computed at runtime with Painless script. I could event think about implementing it in tracardi REST API. Maybe it is even possible to make it a part of GraphQL - do not know right now. You may need to change the profile mapping to do that.  

There is a third option, but it is not available right now. I am working on a metric worker that will run inside tracardi and can perform different tasks in background. For that it needs a simplified math script language to perform these task so a work on it will take some time. 

An last approach is that you connect directly to elastic and run queries on the profile index that will decrease the interests over time. 

### Task for Tracardi community

- [ ] Check how to add painless script at runtime to profile mapping. 
- [ ] Check if there is an option to add dynamically fields to GraphQL Schema.

**Comment by atompie** [comment]
@bceyssens I moved this issue to discussions: https://github.com/Tracardi/tracardi/discussions/223 We can continue there.

**Comment by bceyssens** [comment]
@atompie which components have already been finished?

**Comment by atompie** [comment]
@bceyssens We have a calculator ([http://docs.tracardi.com/flow/actions/calculator_action/](http://docs.tracardi.com/flow/actions/calculator_action/)) and time difference [http://docs.tracardi.com/flow/actions/calculate_time_difference_action/](http://docs.tracardi.com/flow/actions/calculate_time_difference_action/)  plugins. With these, you should be able to calculate the drop in interest. 

You may need to tick append input to output in the advanced runtime configuration to pass data from one plugin to another. 
This is available in the new version for every plugin. It is in the docker hub already/

![Screenshot from 2022-01-24 11-27-20](https://user-images.githubusercontent.com/16271564/150766272-646da260-a674-4723-999f-cf181c2d3f59.png)
