### ISSUE TITLE
Validation error when creating segment

### ISSUE THREAD

**Issue by bceyssens** [Tracardi/tracardi#227]
@atompie,

When creating a segment, I'm not getting past the condition validation:

Conditions:
`stats.visits>10`

Error on validation request:
`{"detail":"No terminal matches '.' in the current parser context, at line 1 col 6\n\nstats.visits>10\n     ^\nExpected one of: \n\t* LPAR\n"}`

**Comment by bceyssens** [comment]
@atompie that works perfectly, thank you! Perhaps the description should be more clear?

`Condition example: stats.visits>10 AND properties.public.boughtProducts>1`

**Comment by atompie** [comment]
You're right I have missed that
