### ISSUE TITLE
Ability to access assigned machine name for segments

### ISSUE THREAD

**Issue by danzaar** [Tracardi/tracardi#263]
Hello @atompie 
In addition to the given name, we would also like to be able to access the generated machine name for each segment returned from the Tracardi API. Is it possible to add this?

![Screenshot from 2021-12-06 10-59-30](https://user-images.githubusercontent.com/54250476/144827519-7874765f-fc42-44b3-a01d-2245bdd50f07.png)

**Comment by atompie** [comment]
@danzaar Yes. Correct me if I am wrong. You would like to have the same generate name (segment-id) as as the system assigns to profile when it is segmented to the given segment.

**Comment by danzaar** [comment]
Yes that is correct.

**Comment by atompie** [comment]
Ok it can be done.

**Comment by atompie** [comment]
@DawidekZagajnik Add dynamically computed field

Example
```
class Tags(BaseModel):
    values: Tuple['str', ...] = ()
    count: int = 0

    class Config:
        validate_assignment = True

    @root_validator
    def total_tags(cls, values):
        values["count"] = len(values.get("values"))
        return values
```

**Comment by DawidekZagajnik** [comment]
sure

**Comment by DawidekZagajnik** [comment]
done, @atompie could you please check my PRs?
