### ISSUE TITLE
String validator does not validate http://localhost URL

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#265]
String validator does not validate correctly http://localhost URL, when selected URL validation.

String validator is moved 

to:

* https://github.com/Tracardi/tracardi/blob/master/tracardi/process_engine/action/v1/strings/string_validator/plugin.py

![Screenshot from 2021-12-07 11-16-54](https://user-images.githubusercontent.com/16271564/145010951-8706e2b2-5d43-47c6-8255-97fb49602303.png)

**Comment by patromi** [comment]
https://github.com/patromi/tracardi-string-validator added

**Comment by atompie** [comment]
@patromi the plugin was moved form your repo to tracardi repa and is in:

https://github.com/Tracardi/tracardi/blob/master/tracardi/process_engine/action/v1/strings/string_validator/plugin.py

And the solution you provided in your repo adds new validation type while it should be picked by the existing URL regex. Maybe the existing regex is not correct.
