### ISSUE TITLE
Incorrect IP address

### ISSUE THREAD

**Issue by bceyssens** [Tracardi/tracardi#344]
The event has an incorrect IP address when Tracardi is running behind a reverse proxy (nginx, varnish, ...). In that case the x-forwarded-ip request header should be used to retrieve the visitors IP address.

**Comment by atompie** [comment]
@bceyssens I am considering an explicit configuration for this use case. We will need to start tracardi with env USE_X_FORRWARDED_IP="header name that passes the IP information".

eg.

```
USE_X_FORRWARDED_IP="x-forwarded-ip"
```

Without explicit configuration when tracardi is installed without reverse proxy then it could be every easy to forge the ip address od the client.

**Comment by bceyssens** [comment]
@atompie yes, I don't think there's another solution for this problem. Adding new configuration is OK.

**Comment by atompie** [comment]
Done. New docker is on its way.

**Comment by atompie** [comment]
@bceyssens With new docker use -e USE_X_FORWARDED_IP="x-forwarded-ip" to get IP from header

**Comment by bceyssens** [comment]
@atompie it is now working correctly!
