### ISSUE TITLE
Plugin: regex string replace plugin

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#348]
This plugin should replace string based on regex expression

# Config

```
{
 "string": "payload@value"
  "find_regex" : "/[a-z]+/u",
  "replace_with": "payload@value"
}
```

Should return new value on the output port "replaced" or on the "not_found" port if the value was not found. 
"replace_with" and "string" can be simple strings as well.

**Comment by DawidekZagajnik** [comment]
that's mine
