### ISSUE TITLE
JSON Schema validation plugin quicks

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#353]
Wrong validation schema results in OK port being triggered.

```
{
  "payload@...": {
    "typesss": "objectsss"
  }
}
```
![Screenshot from 2022-01-16 13-33-30](https://user-images.githubusercontent.com/16271564/149660138-711e8f3d-be06-41c8-9451-716e979ae529.png)

![Screenshot from 2022-01-16 13-30-26](https://user-images.githubusercontent.com/16271564/149660123-14fa943c-b0bf-4163-94db-585281b93cb9.png)

**Comment by DawidekZagajnik** [comment]
That's the matter of validation process in jsonschema library. Validation allows any value under any unproper key, just not considering it while using schema.
