### ISSUE TITLE
Plugin: Get the number of records from database on query

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#380]
# Task

Write a plugin that will query elastic and send a query_string 

Example:
```
session.context.browser.url: "http://localhost"
```

 to a given index (event, session, profile) and return the number of records.

You can also specify a time period link -15m

Thre is a very similar plugin Count_Events take a look at it.

**Comment by DawidekZagajnik** [comment]
leaving some notes here 
![image](https://user-images.githubusercontent.com/60825727/154858256-5169b2ed-37d9-4da6-89fe-339be39ca3a3.png)
