### ISSUE TITLE
Deep categorization error

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#389]
All models like:

* VOC Banking
* VOC Generic
* etc.
return <StreamReader eof e=ClientConnectionError('Connection closed')>

**Comment by DawidekZagajnik** [comment]
This issue seems to be somehow related to API support for certain models
![image](https://user-images.githubusercontent.com/60825727/155586481-7fbd7fd8-4610-4297-934f-1adfa158a8cf.png)
