### ISSUE TITLE
Check if listed endpoint are used

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#404]
# Task

Check if listed endpoints are used. Both on backend and frontend.

* "/purchases/profile/{profile_id}"
* get("/projects"
* get("/project/{id}"
* post("/project"
* delete("/project/{id}"
* get("/session/{id}"
* delete("/session/{id}"
* get("/sessions/refresh"

**Comment by DawidekZagajnik** [comment]
From full-text search performed in GUI repo:
GET /purchases/profile/{profile_id} is not used
GET /projects is used in TuiTaggerFlow.js
GET /project/{id} is not used
POST /project is used in TuiTaggerFlow.js
DELETE /project/{id} is not used
GET /session/{id} is not used
DELETE /session/{id} is not used
GET /sessions/refresh is not used

Hope this helps
