### ISSUE TITLE
Plugin: Convert JSON to payload

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#418]
Convert JSON from referenced value to payload. 

# Config

```
{
"to_object": "event@properties.topic"
}
```

Returns object in Payload port or error on Error port.

**Comment by abant07** [comment]
Hello @atompie 

Is this issue about the converting the value: {"to_object": "event@properties.topic"} to payload, either on a payload port ot error port?

Thanks

**Comment by atompie** [comment]
@abant07 Ohh sorry I did not notice you would like to contribute. I already did this task. Would you like me to find you another ### "good first issue"

**Comment by abant07** [comment]
@atompie 

Yes that would great!

Thanks

**Comment by abant07** [comment]
Hey @atompie 

I was also curious about this issue. I looked at the latest commit that was in the tracardi folder, which was converting a JSON file into a payload. I was wondering what exactly did you do to convert a JSON to a payload. In other words, would be able to share the steps you took?

Thanks

**Comment by atompie** [comment]
@abant07 Sure. 

The code this is executed is in:

```python
async def run(self, payload):
        dot = self._get_dot_accessor(payload)
        json_string = dot[self.config.to_data]
        try:
            result = json.loads(json_string)
            return Result(port="payload", value={"value": result})
        except json.JSONDecodeError:
            return Result(port="error", value={"value": payload})
```

The actual converting is very simple and it it in line:

```
json.loads(json_string)
```

This line:

```
dot = self._get_dot_accessor(payload)
```

Creates an object called dotAccessor and it is responsible for this. [http://docs.tracardi.com/notations/dot_notation/](http://docs.tracardi.com/notations/dot_notation/)

```
json_string = dot[self.config.to_data]
```

This reads a reference to data that is configured in config.to_data. 

And the rest is just simple json conversion and returning results on ports. 

If you would like a full introduction to the project and some tutorial on how to white plugins we can orginaize this. 
There are also some tutorials on out youtube channel.
