### ISSUE TITLE
CiviCRM Integration

### ISSUE THREAD

**Issue by mcollopy** [Tracardi/tracardi#436]
Hi Tracardi team - love your work!

CiviCRM is a popular open source CRM system popular with not-for-profits in particular and Tracardi integrtation would be agreat opportunity for the respective platforms.
About CiviCRM https://civicrm.org/
API https://docs.civicrm.org/dev/en/latest/api/

It would be great to have an integraton within Tracardi to connect with any instance of CivicRM
- the api calls on standard data but I believe custom data as well
- there are many standard tables with standard fields
- custom data is stored in custom tables, whereby the field confi data is stored in standard field config tables

Let me know what info you need to be able to work on a CiviCRM integration
- I can provide access to an instance of CiviCRM if that helps

Manty thanks, MC

**Comment by atompie** [comment]
@mcollopy If you could send us access data for any CiviCRM instance that could speed up everything as we would not have to learn how to install CiviCRM. Please send it via e-mail to office@tracardi.com. Thanks.

**Comment by atompie** [comment]
# Reference links

* [Setting up API Key](https://civicrm.stackexchange.com/questions/9945/how-do-i-set-up-an-api-key-for-a-user)

**Comment by DawidekZagajnik** [comment]
@mcollopy Hi, which version os CiviCRM are you using? I mean Drupal/ Wordpress etc. I would also want to know what is the difference between these versions

**Comment by mcollopy** [comment]
@atompie DONE I've created a user on a demo system and sent the invitation to login to office@
https://civi.audienceware.com/

@DawidekZagajnik CiviCRM is the same whichever CMS integrates with it - there'almost no difference to CiviCRM itself in terms of database, API etc.
The only difference is how the CMS integrates with it, and the differences are minor.
As far as Civi is concerned, the table civicrm_uf_match just contains the contact_id and uf_id (CMS user ID) pairing for the purpose of syncing contact with user.
All the CRM operations and API calls are the same.

Thanks for being on board - I am available to help you in any way I can, thanks.

**Comment by atompie** [comment]
@mcollopy Got your login data. Thanks, already logged in. Got a question though. I see data in the system I assume that this is demo data? Am I right?

**Comment by mcollopy** [comment]
@atompie Yes it's the standard demo data provided by Civi as an optional install - appropriate for a demo like this.
So no confidentiality issues!

**Comment by DawidekZagajnik** [comment]
@mcollopy so I understand that we do not have to worry about corrupting your production data in any way, am I right? Should we pay attention to what we do or is this just a playground for us?

**Comment by mcollopy** [comment]
Yes you are right - don't worry about corrupting data - it's just demo data and is backed up.  
It's a playground if you want - as a demo it was previously restored daily, which I've now disabled.
If you need it backed up let me know, as if you 'break' it you may want it restored to point in time.

**Comment by DawidekZagajnik** [comment]
@mcollopy that's great, thank you so much!

**Comment by DawidekZagajnik** [comment]
@mcollopy Hi, I'm starting to work on CiviCRM integration shortly and I need to know what is the first, basic functionality that you'll need to be included. Is it contact adding?

**Comment by DawidekZagajnik** [comment]
Hi @mcollopy, I see the first issue here. The only way for us to integrate Civi is using REST, and Civi provides two versions of API - v3 and v4, but only v3 is available as REST. It's not deprecated yet, but I'd want to know if using v3 will be a problem for you.

**Comment by DawidekZagajnik** [comment]
Or not, seems like the site is giving contradictory information on v4

**Comment by DawidekZagajnik** [comment]
@mcollopy oh and we'll need site key, you can find it in civicrm.settings.php on your server. It seems to be required for API v3 to work

**Comment by mcollopy** [comment]
V3 should be fine - site key is At4fs8GFkg9C6nSr6He698qqTcSMx0Mt0HrM7xlTsk

**Comment by DawidekZagajnik** [comment]
Alright, thank you for responding at the weekend, means lot for us

**Comment by DawidekZagajnik** [comment]
@mcollopy could you check if SSL certs for your domain are all up-to-date? Making requests to API works only if I set verify_certs equal to false and it prevents development from moving forward. Otherwise I get error info about SSL certificates being not up to date

**Comment by mcollopy** [comment]
@DawidekZagajnik we use Letsencrypt for all our sites and they're updated every 3 months.
The current cert visible via the front end expired June 2022 - see screenshot
<img width="1440" alt="Screen Shot 2022-05-01 at 8 41 15 am" src="https://user-images.githubusercontent.com/1475720/166124979-e197e42e-d25d-470e-8565-ecaeea7435e1.png">

I'm not familiar with the verify_certs  setting - is that on the Civi or Tracardi side?
If on the Tracardi site, does that mean the Tracardi origin needs to be able to connect to the Civi server via SSL and needs a cert on the Tracardi side to make the call?

**Comment by DawidekZagajnik** [comment]
@mcollopy It's on Tracardi site - that's the setting of HTTP client making request to Civi API. If the protocol is HTTPS, then the client takes certs and tries to verify them - that's the point where the error occurs. It did not happen with any HTTP or HTTPS REST API before, so I'm as suprised as you are.

**Comment by DawidekZagajnik** [comment]
Alright, I just got rid of it, thanks for your effort

**Comment by DawidekZagajnik** [comment]
@mcollopy first draft version of the plugin is ready and waits to be merged into master branch. It should be available as docker image shortly. Plugin has no documentation for now, so let me know if you need some help. You can also join our Slack and DM me for more convenient communication.

**Comment by mcollopy** [comment]
@DawidekZagajnik sounds great - looking forward to trying it out!

**Comment by mcollopy** [comment]
Hi @atompie it's not closed yet - we're just working on a MySQL plugin to backload contacts data, then will resume here for current contacts, thanks.

**Comment by atompie** [comment]
Hi @mcollopy we have prepared a generic import where you can import any dada from MySQL. Is there a use case that it does not cover. If so could you describe it here. Thanks :)

**Comment by mcollopy** [comment]
@atompie yes I saw the update on Slack and watched the video, haven't tried it yet but will provide feedback, thanks.

**Comment by atompie** [comment]
Closing this issue. If new functionality is needed or there are any issues please open a new issue.
