### ISSUE TITLE
Relative datetime range filter is not used when using the filter field

### ISSUE THREAD

**Issue by bceyssens** [Tracardi/tracardi#512]
When the filter field is filled, the other filter values are ignored. Eg: the relative datetime range filter.

Not working (all results, 3 days):
![Schermafdruk van 2022-06-16 13-48-10](https://user-images.githubusercontent.com/7702573/174063420-a32649bb-d6cf-4632-9195-f3c1fa70539e.png)

Working (results for 12 hours):
![Schermafdruk van 2022-06-16 13-48-00](https://user-images.githubusercontent.com/7702573/174063426-5de34228-16e2-4434-9dc3-9e0ce759da08.png)

**Comment by DawidekZagajnik** [comment]
fixed
