### ISSUE TITLE
Bug when triggering node multiple times

### ISSUE THREAD

**Issue by DawidekZagajnik** [Tracardi/tracardi#519]
Plugins that modify their own config, can do it only one time most of the time, for example something like:
```python
self.config.path = dot[self.config.path]
```
results in self.config.path being already evaluated in the next .run method call. This makes it impossible to run node differently according to given payload (required when node has more than one "in-edge" or for loop implementation).

One of examples:

![Image](https://user-images.githubusercontent.com/60825727/174634756-407b5070-dd53-4b0b-b933-beea6b1d76c8.png)

![Image](https://user-images.githubusercontent.com/60825727/174634817-d3ab582b-926e-4084-9795-caf4563f8b90.png)

![Image](https://user-images.githubusercontent.com/60825727/174634856-c9d7889a-75b3-4f36-82ff-4946d6f34cc5.png)

![Image](https://user-images.githubusercontent.com/60825727/174634929-3d5a7de7-9bfd-4a09-9fd5-e51002837d57.png)

![Image](https://user-images.githubusercontent.com/60825727/174634984-140b0f59-0ef7-43a8-b7a6-e93f66d79426.png)

in THIS PARTICULAR example this is due to:

![Image](https://user-images.githubusercontent.com/60825727/174635151-22971ba4-6613-467a-80bf-677dfd337ff1.png)

in LogAction run method

**Comment by DawidekZagajnik** [comment]
Possible fixes:
1. Make every plugin configuration read-only (there is an option in Pydantic BaseModel config). Refactoring required here though
2. Save plugin configurations in Node object and then pass new one from memory every time the node is triggered (not initializing the new ActionRunner subclass instance though, maybe make a method like .reset_config() or so)

**Comment by atompie** [comment]
Implementing invariant on dot notated properties can catch the errors early in the coding process.
