### ISSUE TITLE
Node reaaragne moves flow to the left.

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#528]
Node rearrange moves flow to the left.

It should keep it centred. Probably the centre is not 0.0. To reproduce rearrange the flow save it and refresh the page.

![Screenshot from 2022-06-27 18-22-37](https://user-images.githubusercontent.com/16271564/175989212-fea18111-b888-4adf-a513-6c28de49874d.png)

**Comment by DawidekZagajnik** [comment]
centre is at 0, 0, pane is not centred

**Comment by DawidekZagajnik** [comment]
This was a front-end issue, ReactFlow was placed so that (0, 0) was not visible by default

**Comment by atompie** [comment]
@DawidekZagajnik This still does not work. See video

[error.webm](https://user-images.githubusercontent.com/16271564/176551348-eee909ba-6bed-427a-b7c8-1c9bae0312a1.webm)

**Comment by atompie** [comment]
@DawidekZagajnik Sorry my mistake. It is working.
