### ISSUE TITLE
ElasticSearch Indexes replicas

### ISSUE THREAD

**Issue by stefaanneyts** [Tracardi/tracardi#533]
Hi

Some indexes (tracardi-session, tracardi-event, tracardi-profile) are configured to use replicas. This results in a "yellow" health status on a single-node ElasticSearch. As there is only one node, the replica shards stay unassigned.

Maybe an extra setting is required? Or maybe Tracardi could auto-detect the ES architecture and don't use replicas when a single node setup is detected?

Kind regards

Stefaan Neyts
Tech Lead Back-end
Duo nv (part of the make it fly group)
Belgium

**Comment by atompie** [comment]
@stefaanneyts hello thanks for pointing a good solution for this issue. Though I do not know if there is a simple way to find out if es is in single node mode. 

As a second thought there may be the information on the es info page. 

We will solve this issue on the 0.7.1 version:)

**Comment by atompie** [comment]
Yep, there is the info of a number of nodes. We need to use it during installation to decrease the number of replicas.

![Screenshot from 2022-07-03 01-46-29](https://user-images.githubusercontent.com/16271564/177019245-15737181-5833-40ac-bb83-28c4cb00591b.png)

**Comment by atompie** [comment]
After a quick inspection of env variables of version 0.7.1 I see we have ELASTIC_INDEX_REPLICAS where manually we can set no of replicas.  Only installation script could decrease it if signal node ES is installed.

**Comment by atompie** [comment]
Now Tracardi auto decreases the number of replicas for the single node cluster. For the cluster with more than 1 node, you have to decrease it manually in the EVNs, because there can be some cases when the number of nodes is less than expected for a short period of time and you still need a defined number of replicas.
