### ISSUE TITLE
Empty folders in Mautic plugins

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#579]
Check if there are used for some reason. 

![Screenshot from 2022-07-16 01-10-20](https://user-images.githubusercontent.com/16271564/179322954-16356636-33ac-4602-8e5d-96875fded802.png)

**Comment by DawidekZagajnik** [comment]
these are your local directories - that's how Git works - files are recognized by their path, directories are not considered at all. Just remove them locally and you'll see that Git does not detect any changes.

**Comment by atompie** [comment]
Done in 0.7.1
