### ISSUE TITLE
Data exists throws an error on event properties

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#580]
Maybe there is something wrong with uppercase. And it works on production but not in debugging. 

![Screenshot from 2022-07-16 01-26-45](https://user-images.githubusercontent.com/16271564/179323958-a58c3a16-8700-4ce0-b351-40e669237945.png)

![Screenshot from 2022-07-16 01-33-32](https://user-images.githubusercontent.com/16271564/179324382-8b4fe34d-d5bc-486f-ab54-2d95d5b6a76f.png)

![Screenshot from 2022-07-16 01-34-39](https://user-images.githubusercontent.com/16271564/179324460-11e5dfe2-8d2c-45ee-a9ad-5ab1af97f299.png)

**Comment by DawidekZagajnik** [comment]
that's expected behavior - check lines from 56 to 95 in tracardi.process_engine.action.v1.flow.start.start_action.py.
Event type is not specified, thus Start action creates new event of type debug-event-type and empty properties. To be closed in my opinion

**Comment by DawidekZagajnik** [comment]
second thing is that false edge from Data exists was connected to Copy data
