### ISSUE TITLE
Check permission for all user roles.

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#595]
Log in with different roles and check if everything works. 

Known bugs:

* Log-in as a maintainer role and go to migration - you will be logged out. (probably because of the laving role in API)
* Login as a developer and go to settings - you will be logged out. (probably because of the laving role in API)
* Loggin out and missing permissions are all over the system.

**Comment by DawidekZagajnik** [comment]
first fixed

**Comment by DawidekZagajnik** [comment]
admin is OK
