### ISSUE TITLE
Content for mailchimp sending email is not saving. 

### ISSUE THREAD

**Issue by bobsburgers** [Tracardi/tracardi#615]
its latest as of right now. 
current commit 3b2c666a75121f0179657c20e06523c86fa22028

just add start and end with mailchimp transactional. Setup a mailchimp resource(token). configure mailchimp transactional page. Add all the fields. 
Expected. Should be able to add seperate text and html versions of the email. Not sure what the json is for. When i click save I expect them to save

what happens?
i come back to it and its not there. everything else has saved properly. but text json and html tabs are all empty. 
![image](https://user-images.githubusercontent.com/7756504/181621931-d56207b6-d1c5-45a3-a02c-176f3c517501.png)

**Comment by bobsburgers** [comment]
it disappears even when you put something in json. Which it does not allow. 

`    @validator("type")
    def validate_type(cls, value):
        if value not in ("text/plain", "text/html"):
            raise ValueError("Message content type must be either HTML or plain text.")
        return value`

**Comment by atompie** [comment]
Thank you for reporting this we are after it.

**Comment by DawidekZagajnik** [comment]
gonna take care of this
