### ISSUE TITLE
Use select with indices in ES plugin

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#618]
Now configuration looks like this

![Screenshot from 2022-07-29 21-45-51](https://user-images.githubusercontent.com/16271564/181833175-08fbd45b-a01a-4ca8-807b-c56fd056db71.png)

But could use a select with indices the same way as in import
![Screenshot from 2022-07-29 21-46-07](https://user-images.githubusercontent.com/16271564/181833252-86954713-6df0-4cab-bf60-44589d42a05e.png)
t

**Comment by atompie** [comment]
![Screenshot from 2022-08-01 22-48-16](https://user-images.githubusercontent.com/16271564/182245029-dbd0fab6-5f2a-4f23-9eb2-6c855577998c.png)

**Comment by atompie** [comment]
@DawidekZagajnik After running this plugin I found some fixes that have to be made to this PR.

```python
    @staticmethod
    async def fetch_indices(config: dict):
        config = ElasticSourceConfig(**config)
        resource = await storage.driver.resource.load(config.source.id)
        credentials = ElasticCredentials(**resource.credentials.production)

        if credentials.has_credentials():
            client = AsyncElasticsearch(
                [credentials.url],
                http_auth=(credentials.username, credentials.password),
                scheme=credentials.scheme,
                port=credentials.port
            )
        else:
            client = AsyncElasticsearch(
                [credentials.url],
                scheme=credentials.scheme,
                port=credentials.port
            )

        indices = await client.indices.get("*")
        indices = indices.keys()

        return {
            "total": len(indices),
            "result": [{"name": record, "id": record} for record in indices]
        }
```
Why this code uses AsyncElasticsearch. We have put a lot of effort to make a ES driver to wrap AsyncElasticsearch in one place. Using AsyncElasticsearch outside driver is forbidden. 

Take a look at raw driver it has methods for fetching indices:

![Screenshot from 2022-08-01 23-04-13](https://user-images.githubusercontent.com/16271564/182246373-be9f3723-99d8-480b-ba57-05c67606c36c.png)

It is also possible that the endpoint for indices also exists. But maybe it does not work as a list of named entities.

**Comment by DawidekZagajnik** [comment]
Yeah, but ElasticSearch (resource) can be different ElasticSearch than the one connected to Tracardi. That's why a new client has to be used.

**Comment by DawidekZagajnik** [comment]
just like with MySQL or MongoDB connectors
