### ISSUE TITLE
Mail to Tracardi bridge

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#648]
**Describe the solution you'd like**
Make a bridge that would report every mail that comes to defined e-mail address.

**Additional context**
Once read emails should not make to tracardi as events.

**Comment by bobsburgers** [comment]
i was thinking about this myself a few weeks ago. The best way i have found is using a mail service that does api on new email. like https://github.com/postalserver/postal offers. there are some other solutions as well. 

if you do want to be from the system "pull" style i used this once before https://github.com/bamthomas/aioimaplib and it has support for async idle waiting for email. Then i just did a cron job to make sure its always running. if you do a lot you start to notice it processing wise but has to be a whole lot in my experience.

**Comment by atompie** [comment]
Done in 0.7.4
