### ISSUE TITLE
/install exposing info on gui api deployment

### ISSUE THREAD

**Issue by bobsburgers** [Tracardi/tracardi#655]
**Describe the bug**
On gui api you can just go to /install and it gives your login and seemingly your password back to you. 

**To Reproduce**
1. setup gui api
2. go to /install
3. See error

**Expected behavior**
I dont expect to have my login show up anyplace potentially publicly accessible. even if it is just the username. 

**Additional context**
`{"missing":[],"admins":{"total":1,"result":[{"password":"e1057a7a3f19e8718d323908d2e2ee*******","full_name":"Default Admin","roles":["admin"],"disabled":false,"id":"admin@****.com","email":"admin@***.com","token":null}]},"missing_template":[],"missing_alias":[],"schema_ok":true,"admin_ok":true}`

**Comment by bobsburgers** [comment]
I checked my web deployment today and noticed that it also shows the same.

**Comment by atompie** [comment]
Fixed in version 0.7.2
