### ISSUE TITLE
Elastic email plugins do not use event loop and are blocking

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#657]
Describe the bug
----------------------

Elastic email plugins do not use asyncio event loop. The ADD CONTACT plugin delivers the async parameter that uses threads (not the best solution) but `send bulk email` and `send transactional email` does not have async execution and are blocking. If there is network problem it can block the whole server for quite some time .Therefore this plugin must be rewritten to use the regualr REST API. And `tracardi.service.tracardi_http_client` should be used to call the API. 

Example usage 
```python
 async with HttpClient(
            self.retries,
            [200, 201, 401],
            headers={
                "Accept": "application/json",
                "Content-Type": "application/json",
                "api-token": self.api_key
            }
        ) as client:

            async with client.post(
                    url=f"{self.api_url}/api/3/contacts",
                    json={"contact": data}
                ) as response:

                    if response.status != 201:
```  

Also the endpoint returns 400.

Expected behavior
-------------------------

- [ ] None blocking execution and 200 response from Elastic email endpoint.
- [ ] Documentation of the resource on how to get the correct API KEY

**Comment by bobsburgers** [comment]
solved https://github.com/Tracardi/tracardi/issues/657

**Comment by atompie** [comment]
Done in 0.7.2
