### ISSUE TITLE
Attempt to decode json with unexpected mimetype

### ISSUE THREAD

**Issue by bobsburgers** [Tracardi/tracardi#670]
Describe the bug
------------------------

When using api connection that respond with html we get a decode error. In this case and apparently its common enough.
https://stackoverflow.com/questions/48840378/python-attempt-to-decode-json-with-unexpected-mimetype

`Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.elasticemail.co`

To Reproduce
------------------------

1. create a resource API endpoint
2. create a workflow
3. add remote api call and create a call to an api that returns text/html content-type but really has json. (elasticemail works)
4. run debug. 

Expected behavior
----------------------------

I expect a returned success is a success and not depend that on the mimetype. json responses should be proccessed as json even when it claims to be text/html

Recommended fix
----------------------------
we have a few options

this addition to api_call\plugin.py starting like 76

`                    try:
                        content = await response.json()

                    except JSONDecodeError:
                        content = await response.text()

                    except ContentTypeError:
                        content = await response.json(content_type='text/html')`

`                    try:
                        content = await response.json()

                    except JSONDecodeError:
                        content = await response.text()

                    except ContentTypeError:
                        content_type = response.headers.get('Content-Type').split(';')
                        content = await response.json(content_type=content_type )`

or seems like a worse idea but does work. 

`                    try:
                        content = await response.json(content_type=None)

                    except JSONDecodeError:
                        content = await response.text()
`

**Comment by bobsburgers** [comment]
https://github.com/bobsburgers/tracardi/commit/3b8d82e68fee02777c3ea676e58567510e87fcd3

**Comment by atompie** [comment]
https://github.com/bobsburgers/tracardi/commit/3b8d82e68fee02777c3ea676e58567510e87fcd3 Added to plugin in 0.7.3-dev
