### ISSUE TITLE
Feature: Copy/Duplicate things

### ISSUE THREAD

**Issue by bobsburgers** [Tracardi/tracardi#695]
**Is your feature request related to a problem? Please describe.**
I often have to make slightly diffrent version of the same thing. Usually flows or flow nodes is when it would be most helpful.

**Describe the solution you'd like**
A button to duplicate a workflow or a workflow node.

**Describe alternatives you've considered**
the only option is to remake the same thing. 

**Additional context**

**Comment by atompie** [comment]
Done in 0.7.2
