### ISSUE TITLE
Github client

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#712]
**Is your feature request related to a problem? Please describe.**
Create a client that can interact with github via API 

**Describe the solution you'd like**
I would like to be able to connect to with API with access-token and perform the following operations: 

* add comment to issue
* get comments for issue
* get issues from repo. 
* Find an issue.
* open discussion.

**Additional context**
Usefull links:
- https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api
- https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
- https://docs.github.com/en/rest/issues/comments#create-a-comment

**Comment by detronetdip** [comment]
Hey i am interested in this please tell me what are the operation you want to perform from the clientside?

**Comment by atompie** [comment]
@detronetdip Hello we would like to post a comment on an issue. And maybe start a discussion. This would be a good start. IF you can manage that then I could come up with a set on new operations.

**Comment by detronetdip** [comment]
Well looks interesting. Let's have a discussion on it.

**Comment by atompie** [comment]
@detronetdip Sure we can start here: https://github.com/Tracardi/tracardi/discussions/715

**Comment by atompie** [comment]
One prerequisites that is required the client must be async. We recommend to use internal Tracardi client: `tracardi/service/tracardi_http_client.py`

use example in our code:

```python
timeout = aiohttp.ClientTimeout(total=self.timeout)
        async with TracardiHttpClient(self.retries, 200, timeout=timeout) as client:
            params = {
                'key': self.key,
                'txt': string
            }
            async with client.request(
                    method="POST",
                    url=str("https://api.meaningcloud.com/lang-4.0/identification"),
                    data=params
            ) as response:
                result = {
                    "status": response.status,
                    "body": await response.json()
                }

                return response.status, result
```

**Comment by atompie** [comment]
Hi @detronetdip Are you still up for this task?

**Comment by atompie** [comment]
@knittl Would you like to take care of this task?

**Comment by knittl** [comment]
@atompie sure, sounds interesting. I'll see what I can do. But I won't be able to have it ready before hacktober ends. Still want to give it a shot :)

**Comment by atompie** [comment]
@knittl perfect. No hurry. If you want to contribute to tracardi after hacktoberfest you are welcome. BTW This client will become a part of another plug-in for managing GitHub issues with tracardi. So there will be more tasks if you want to contribute.

**Comment by knittl** [comment]
@atompie I have taken a first cursory look at this and was able to implement a simple plugin to query the issues of a repository. However this resulted in several questions:

* There's already the "Remote API call" plugin (connectors/api_call) which seems to be able to do this already. Without headers for public repositories and with for private repositories with a header. I assume the GitHub plugin is intended as a more user-friendly alternative to the api_call plugin?
* How much code can and should be reused? Is it possible to "compose" or "combine" plugins? Possibly users can do that themselves, creating reusable and sharable components/component groups? Or is it better to copy&paste code to keep plugins independent?
* There are existing libraries to integrate with GitHub such as [PyGithub](https://github.com/PyGithub/PyGithub). Should/may those be used? We only import them as dependency and the license seems to be LGPL-3
* Should this be a single "GitHub" plugin or is the goal to have one plugin per action, e.g. separate "List issues", "Create issue", "Start discussion", "Search issues" plugins? I'm not sure how a single plugin would handle the different actions and configuration?
* Where should the plugin take the data for the request, such as the repo path. Should it come from the node's configuration, from the event/payload, a resource? For the PAT, a resource definitely makes sense. For the others, I'm not so sure. Can users specify where they want the data to be taken from? (Can you recommand an existing plugin which I can look at for inspiration?) I'm especially unsure about how those dot-paths should be used and what the recommended data source is.
* How should the data be returned? Simply return the parsed JSON on the output port? Or do some pre-processing? What is expected to happen with the result data? To have a starting point, this can be defined for "List issues" for now and the others later.

I can share the WIP code tomorrow, perhaps this is easier to discuss with real code :) But it basically boils down to:

```py
            async with client.request(
                    method='GET',
                    url=f'{self.config.api_url}/repos/{self.config.owner}/{self.config.repo}/issues',
                    headers={'accept': accept},
            ) as response:
                return Result(
                    port='payload',
                    value={
                        'result': {
                            "status": response.status,
                            "body": await response.json()
                        }
                    })
```

Looking forward to your answers.

**Comment by atompie** [comment]
@knittl 

1. Yes we create separate plugins for less technical user to use it. Basically you can use Remote API to call many services but 80% of the users are not very technical savvy to use it out of the box. 

2. We usually reuse the code that is in tracardi library (outside plugins). We do not mix code between plugins or inherit for other plugins because plugins can be moved to microservices so it would be difficult to separate one plugin from another. So to make it simple we use the common code from tracardi/service like `HttpClient` (the same way we want to use Github client but maybe it will be local to the github plugins.) and most of the time it is enough. If we see that there is a lot of code duplication then we separate that code in the tracardi/service. As a rule of thumb we do not allow for example Configs from another plugin. 

3. I saw [PyGithub](https://github.com/PyGithub/PyGithub) an was thinking about using it but there are two blocking issues.The license is not compatible with MIT or Apache 2.0 and it is not asynchronous lib. The second issue is not acceptable as it would block the fast API server every time we use it. 

4. I was thinking separate plugins. It is easier to use it this way and the form is simpler. We do not support conditional fields in the form right know so when we combine plugins we may encounter an issue that form should change depending on the functionality. And that could be very difficult to handle right now. 

5. You go me thinking :)  I think that the repository and its credentials should be in the resource. And based on this resource we can make actions such as getting issue comments, etc. As to dot path I would start without them and when the plugin is almost ready think where it could be useful have data being referenced. So this would be like the last step. 

6. I would return a parsed JSON. I see it as better approach then processed data as if the API breaks the contract and changes the way it returns the data then the user can correct it in the workflow and we do not have to release a fix for this. 

You are right the is as simple as you typed by it might be better to make a facade for the client and have more then just a  client.request. 

Maybe something like client.list_issues() or client.list_issue_comment(issue_id).

**Comment by knittl** [comment]
@atompie Hi, you find the very first draft here: https://github.com/knittl/tracardi/commits/github-plugin-issues. Currently, the issues for a repo can be listed and details for a single issue can be queried.

There are a few things I'm unsure about, especially configuration (e.g. "should owner/repo be part of resource or not" and "should PAT be a separate resource?").

Let me know if the code is heading in the right direction or if it has to be rewritten. My python-fu is not the strongest when it comes to async/await, so that part of the code can definitely be improved.

**Comment by atompie** [comment]
@knittl The code is looking perfect :)

`Should owner/repo be part of resource?`

Well I think repo could be selected inside the plugin. If there is a method in the github API to list repos for one owner then I could show you how to get a list of repos from remote API into the plugin select field. As to owner I thin this should be part of resource. 

I see it this way. 

Resource:

1. API_KEY
3. Owner

Plugin:
1. Repo - as 1 owner can have many repos.

`should PAT be a separate resource?`

What is PAT?

**Comment by knittl** [comment]
@atompie PAT = "Personal Acces Token"; the tokens created by GitHub to enable APIs to impersonate your user.

Why I'm asking about bundling the owner with the API key (the "PAT") is the following: the PAT is bound to a user, not a repo owner. To give an example: you could create a PAT for user/owner "atompie". Since user "atompie" has access to org "Tracardi" this token will allow requests to interact with `Tracardi/*` projects/repos, not only `atompie/*` projects/repos.

Put differently: it's not the case that the PAT is only valid with an owner, but rather the PAT is a replacement for a user. If you use the PAT, you can do anything that the user who created the PAT could do (given that this permission was enabled in the PAT). It just doesn't feel right to me to lock the owner with the key when the key could be used to interact with other repos, but of course I have no problem with implementing it that way.

1 owner can have many repos, 1 PAT can access many repos of a single owner & of many orgs.

> If there is a method in the github API to list repos for one owner […]

Yes, there is. Without a PAT, only public repos are listed, with a PAT the private ones can be listed too.

**Comment by atompie** [comment]
@knittl Ok Now I think I have the whole picture. I think PAT should be in resource (separate). And with plugin we can select the repos. First make it to be typed in by user then we will replace it with the select populated with the data form github.
