### ISSUE TITLE
Missing documention for ActiveCampaign resource

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#713]
**Is your feature request related to a problem? Please describe.**
Add documentation for ActiveCampaign resource. Describe how to obtain token, etc.

There is file already created `manual/en/docs/resources/activecampaign_resource.md` we only need to add steps that describe how to obtain API credentials.

**Comment by ojninja16** [comment]
hi...I would like to work on it...

**Comment by atompie** [comment]
@ojninja16 Sure go ahead. We are happy to get some decent documentation.

**Comment by ojninja16** [comment]
hi @atompie  I have raised a pr #156 in tracardi-api repo for this .....thanks!
