### ISSUE TITLE
Missing Amplitude resource documentation

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#714]
**Is your feature request related to a problem? Please describe.**
Is your feature request related to a problem? Please describe.
Add documentation for Amplitide resource. Describe how to obtain token, etc.

There is file already created `manual/en/docs/resources/amplitude_resource.md` we only need to add steps that describe how to obtain API credentials.

**Comment by ojninja16** [comment]
hi...I would like to work on it...

**Comment by ojninja16** [comment]
hi @atompie i have raised a pr #155 in tracardi-api repo for this....

**Comment by atompie** [comment]
I have read it ad i seems ok. All the necessary info is there. I need to change the name in the system from token to api_key as Amplitude use this word,

**Comment by ojninja16** [comment]
okay...

**Comment by atompie** [comment]
Done in version 0.7.3

**Comment by atompie** [comment]
@ojninja16 I noticed on you profile that you are learning react. Tracardi GUI is in react and maybe you would be interested in this issue: https://github.com/Tracardi/tracardi-gui/issues/203

**Comment by ojninja16** [comment]
Yeah I am still, learning though. It's kind a hard!! ...thanks for noticing....yeah sure I will have a look...thank you for bringing it to my notice....
