### ISSUE TITLE
Missing documentation for MixPanel resource.

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#716]
**Is your feature request related to a problem? Please describe.**
Add documentation for MixPanel resource. Describe how to obtain token, etc.

There is file already created `manual/en/docs/resources/mixpanel_resource.md` in the https://github.com/Tracardi/tracardi-api repo we only need to add steps that describe how to obtain API credentials.

**Comment by ojninja16** [comment]
hi @atompie ,I would do this...

**Comment by atompie** [comment]
@ojninja16  Thanks. Task assigned.

**Comment by ojninja16** [comment]
Hi @atompie , I have raised a PR #164 in Tracardi-api repo....

**Comment by atompie** [comment]
Done in 0.7.3
