### ISSUE TITLE
Missing documentation for RabbitMQ resource

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#720]
**Is your feature request related to a problem? Please describe.**
Add documentation for RabbitMQ resource. Describe how to obtain user, password, what is Virtual Host and connection Timeout.

There is file already created `manual/en/docs/resources/rabbitmq_resource.md` in the https://github.com/Tracardi/tracardi-api repo we only need to add steps that describe how to obtain data for the form.

This is the form that needs to be described
![Screenshot from 2022-10-06 09-47-19](https://user-images.githubusercontent.com/16271564/194248222-9e6fbc5b-2eae-4bcd-afcb-d5c8268b1b83.png)

**Comment by atom540** [comment]
can you please assign this task to me?

**Comment by atompie** [comment]
@atom540 Sure

**Comment by atompie** [comment]
@atom540 Are you still interested in this task?

**Comment by hyprex-deva** [comment]
Can you please assign this task to me.
I would like to do this task as a part of the Hacktoberfest.

**Comment by hyprex-deva** [comment]
Sir, please can you tell me the context behind the RabbitMQ Setting.
A brief description will be enough.

**Comment by hyprex-deva** [comment]
The repo link which you have mentioned is a different repo.
So I have to make the documentation here : https://github.com/Tracardi/tracardi-api/blob/master/docs/resources/rabbitmq_resource.md
Then I have to fork that repo and do a Pull Request, Correct me if am wrong.

**Comment by atompie** [comment]
@hyprex-deva yes you are right.

**Comment by hyprex-deva** [comment]
I created a PR on that repo, please look into that.
If its correct, I would like to work in different issue.

**Comment by atompie** [comment]
@hyprex-deva Would you like to try to code a tracardi plugin? https://github.com/Tracardi/tracardi/issues/727

**Comment by hyprex-deva** [comment]
Am not exactly sure if I could write a code to a plugin, if any of the documentation issues are there I would like to solve that before.

**Comment by atompie** [comment]
@hyprex-deva Sure no problem.

**Comment by atompie** [comment]
@hyprex-deva If you are looking for documentation issues you can take a look here. https://github.com/Tracardi/tracardi/issues/460
