### ISSUE TITLE
Missing Salesforce resource documentation

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#721]
**Is your feature request related to a problem? Please describe.**
Add documentation for Salesforce resource. Describe how to obtain clientId, clientSecret, subDomain.

There is file already created `manual/en/docs/resources/salesforce_resource.md` in the https://github.com/Tracardi/tracardi-api repo we only need to add steps that describe how to obtain data for the form.

This is the form that needs to be described
![Screenshot from 2022-10-06 09-49-19](https://user-images.githubusercontent.com/16271564/194248729-9d808cab-b1a9-4eb4-90dc-1f73ce65312c.png)

Please find in salesforce documentation how to obtain this data.

**Comment by madhavmehndiratta** [comment]
Hi, can I work on this?

**Comment by atompie** [comment]
Yes go ahead @madhavmehndiratta

**Comment by atompie** [comment]
Done in 0.7.3
