### ISSUE TITLE
Missing zapier resource documentation

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#722]
**Is your feature request related to a problem? Please describe.**
Add documentation for Zapier resource. Describe how to open a webhook in zapier that we can send event to.

There is file already created manual/en/docs/resources/zapier_resource.md in the https://github.com/Tracardi/tracardi-api repo we only need to add steps in MD format that describe how to open a webhook.

**Comment by madhavmehndiratta** [comment]
Hi I would like to take up this issue

**Comment by atompie** [comment]
@madhavmehndiratta Sure go head. If you have any questions do not hesitate to ask.

**Comment by madhavmehndiratta** [comment]
The PR has been merged. (https://github.com/Tracardi/tracardi-api/pull/159) 
You can close this issue now.

**Comment by atompie** [comment]
Please find the enclosed PDF with Cluster installation information. If you
would like me to create a kubernetes cluster, I will need access to your DO
account.


Regards
Risto Kowaczewski
