### ISSUE TITLE
Missing scheduler documantation

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#723]
**Is your feature request related to a problem? Please describe.**
Add scheduler documentation

**Comment by hyprex-deva** [comment]
Is this issue under Hacktoberfest ?
If yes, I want to work on this issue.

**Comment by atompie** [comment]
@hyprex-deva It is not - it requires some deep tracardi knowledge and I must do it myself

**Comment by atompie** [comment]
Done in 0.7.3
