### ISSUE TITLE
Missing sendgrid resource documentation

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#724]
**Is your feature request related to a problem? Please describe.**
Add documentation for SendGrid resource. Describe how to obtain token, etc. You will need to go through the sendgrid.com documentation to find you how to obtain token to authenticate API. 

There is file already created `manual/en/docs/resources/sendgrid_resource.md` in the https://github.com/Tracardi/tracardi-api repo we only need to add steps that describe how to obtain API credentials.

**Comment by CypherpunkSamurai** [comment]
Hello @atompie can I work on this as a part of hacktoberfest? :)

**Comment by devshaki** [comment]
how to create a Token:

Navigate to Settings on the left navigation bar, and then select API Keys.
Click Create API Key.
Give your API key a name.
Select Full Access, Restricted Access, or Billing Access.
If you're selecting Restricted Access, or Billing Access, select the specific permissions to give each category. For more information, see [API key permissions](https://docs.sendgrid.com/ui/account-and-settings/api-keys#api-key-permissions).
Click Create & View.
Copy your API key somewhere safe. For security reasons, do not put it directly in your code, or commit it somewhere public like GitHub.

**Comment by CypherpunkSamurai** [comment]
Thank you @devshaki. I'll wait for confirmation and get coding soon :)

**Comment by atompie** [comment]
@CypherpunkSamurai sure go ahead

**Comment by atompie** [comment]
@CypherpunkSamurai PR merged an #hacktoberfest-accepted

**Comment by CypherpunkSamurai** [comment]
Thanks a lot @atompie @devshaki !! :D
