### ISSUE TITLE
Missing InfluxDB resource documentation

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#725]
__Is your feature request related to a problem? Please describe.__
Add documentation for InfluxDB resource. Describe how to obtain token from https://www.influxdata.com/.

There is file already created manual/en/docs/resources/influxdb_resource.md in the https://github.com/Tracardi/tracardi-api repo we only need to add steps that describe how to obtain the token.

Please find it on the https://www.influxdata.com/. It should be somewhere in the docs.

**Comment by atompie** [comment]
@ojninja16 sure

**Comment by ojninja16** [comment]
hi @atompie ...just wanted to make sure, I need to add documentation for **obtaining the token  for authenticating API requests right**??? and one other issue ....This here in the SS there are 2 options for documentation...which one exactly is implemented here......Thanks
![image](https://user-images.githubusercontent.com/98155899/194380824-701e3e45-bb72-4dbb-a192-e4539b5feca2.png)

**Comment by atompie** [comment]
That's right.

**Comment by atompie** [comment]
Actually I do not remember. Could you check if there is a difference in authentication?

**Comment by ojninja16** [comment]
okay...thanks....I Checked there does not seems to be a difference in the authentication for above two....

**Comment by atompie** [comment]
@ojninja16 I just moved `manual/en/docs/resources/influxdb_resource.md` to `/docs/resources/influxdb_resource.md` Please update your repo.

**Comment by ojninja16** [comment]
Hi @atompie ,I have created a PR for it in tracardi-api repo #158

**Comment by atompie** [comment]
Implemented in 0.7.3
