### ISSUE TITLE
Create plugin that joins strings

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#726]
**Is your feature request related to a problem? Please describe.**
Plugin that joins array referenced in plugin config. This plugin is very simple in terms of python. The challange is to add it as plugin. This is also very simple if you read this http://docs.tracardi.com/plugins/tutorial/part1/

**Describe the solution you'd like**
User defines in plugin configuration what array he would like to split and what is the delimiter character. 

Example of configuration 

```json
{
   "delimiter": ",",
   "string": "event@properties.emails"
}
```

Input:
Workflow payload

Output:
Joined array as string,

**Additional context**
There is a string splitter plugin in the system `tracardi/process_engine/action/v1/strings/string_splitter/plugin.py` it is a very good starting point to write the similar string join plugin. To understand how the plugins work please read http://docs.tracardi.com/plugins/tutorial/part1/. It explains how to write plugins for Tracardi.

**Comment by yk-jp** [comment]
Hi, do you mind me working on this issue?

**Comment by khadeom** [comment]
Hi, how are the issues assigned to new contributors?

**Comment by atompie** [comment]
@yk-jp Sure go ahead. If you have any question please join our slack channel (you can find on our README) or you may ask them here.

**Comment by atompie** [comment]
Hey @khadeom. Sorry bu you came second. But I have very similar task that you could take. It is the same level of complexity so I let myself to assign it to you. If this is OK then go ahead an it is your if not then let me know.  

Here is the task: https://github.com/Tracardi/tracardi/issues/727

**Comment by khadeom** [comment]
Thank you @atompie, i have commented on it now.

**Comment by yk-jp** [comment]
@atompie 
HI, I have a question. Is this input a string, not string list? 
I'm confused with delimiter because output is going to be list. 
I thought I should use `join` method with delimiter to given list and `str type` is outputted.

**Comment by yk-jp** [comment]
@atompie 
Hi, I have a question. Is the input described above a string, not string list?
I'm confused with delimiter because output is going to be a list.
I thought I should use join method with delimiter to given list and str type is outputted.

**Comment by atompie** [comment]
Done in 0.7.3
