### ISSUE TITLE
Remote api call connector issue

### ISSUE THREAD

**Issue by sruthisanthosh1** [Tracardi/tracardi#728]
When calling a remote api that return no body using **REMOTE API CALL CONNECTOR**  the plugin fails because it is trying to parse the  response object.
![image](https://user-images.githubusercontent.com/55072791/194803929-111f09fb-ecbd-41bc-9d4a-fbec1363766f.png)

I am testing this with a test url <https://httpbin.org/status/200>
the plugin should not parse the body if the Content-Length is 0

# Context
This plugin is handled bu the file `tracardi/process_engine/action/v1/connectors/api_call/plugin.py`.

Response handling takes part here:

```python
try:
    content = await response.json(content_type=None)

   except JSONDecodeError:
         content = await response.text()

    except ContentTypeError:
          content = await response.json(content_type='text/html')
```

You can see that Content-Type error is already handled but there may be an issue of parsing empty response.

**Comment by atompie** [comment]
@sruthisanthosh1 Thank you for reporting. I will take care of it.

**Comment by The-Debarghya** [comment]
Hey, can you give some context, then I can try this out.

**Comment by atompie** [comment]
@The-Debarghya Sure, @sruthisanthosh1 reported that when calling an endpoint that returns empty data he encountered an error. He used  https://httpbin.org/status/200 as an URL and it returns Content-type: header text/html and an empty body. 

My first guess it that it caught  by 

```python
 except ContentTypeError:
          content = await response.json(content_type='text/html')
```

but response.json is not able to handle empty body. We need to check for empty body. 

This task will need for you to set up a dev environment of Tracardi to test it out. Here you can read how to do it: http://docs.tracardi.com/development/python_env/

**Comment by atompie** [comment]
@The-Debarghya I assigned you to the issue. If you do not feel like doing it let me know> I will remove you form it.

**Comment by The-Debarghya** [comment]
I tried but couldn't figure out...you can go ahead.
I'm unassigning myself.

**Comment by owaiskazi19** [comment]
Hey @atompie! I started looking into this issue and getting the below error for the URL mentioned above( https://httpbin.org/status/200)

<img width="1292" alt="Screen Shot 2022-10-16 at 6 58 55 PM" src="https://user-images.githubusercontent.com/16099877/196073336-224666c8-fb1f-4877-904c-a980dea81805.png">

**Comment by atompie** [comment]
@owaiskazi19  am not sure if the plug-in is correctly setup. It says that you typed invalid url /proxy/. Could you select a json configuration icon and paste here the Json.

**Comment by owaiskazi19** [comment]
```
{
  "source": {
    "id": "0c839d3c-83be-43da-bab9-2ecf1d84aea8",
    "name": "test"
  },
  "endpoint": "https://httpbin.org/status/200",
  "timeout": 30,
  "method": "get",
  "headers": {},
  "cookies": {},
  "ssl_check": true,
  "body": {
    "type": "application/json",
    "content": "{}"
  }
}

**Comment by atompie** [comment]
@owaiskazi19 I think there are the following issues with the config:
Endpoint should be
```
"endpoint": "/status/200",
```

No need for the url. The resource `test` that you have set here 

```
"source": {
    "id": "0c839d3c-83be-43da-bab9-2ecf1d84aea8",
    "name": "test"
  },
````

Should have the following set-up:
```
{
  "url": "https://httpbin.org"
}
```
Check if in the resources you have:
![Screenshot from 2022-10-17 22-15-40](https://user-images.githubusercontent.com/16271564/196274582-771967f8-69e2-40c5-979e-d1eff6713f4c.png)

**Comment by owaiskazi19** [comment]
That worked. Thanks!
I'm getting a successful API call here and not issue mentioned above though

<img width="1462" alt="Screen Shot 2022-10-17 at 1 41 48 PM" src="https://user-images.githubusercontent.com/16099877/196279133-8e7aa211-e410-4dc4-a872-867c04e9db15.png">

**Comment by Mefpef** [comment]
Hi @owaiskazi19 you are working on this issue right now ?

**Comment by owaiskazi19** [comment]
> Hi @owaiskazi19 you are working on this issue right now ?

Hey @Mefpef! Yes, I am.

**Comment by atompie** [comment]
Done in 0.7.3
