### ISSUE TITLE
Twiter plugins that tweets a message build form text template

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#729]
**Is your feature request related to a problem? Please describe.**
Create a twitter plugin that connects to twitter API and tweets a message.

**Describe the solution you'd like**
Use the following manuals to create a twitter plugin that tweets a message
* http://docs.tracardi.com/plugins/tutorial/part1/
* http://docs.tracardi.com/plugins/tutorial/part2/
* https://www.mattcrampton.com/blog/step_by_step_tutorial_to_post_to_twitter_using_python/

Create a documentation in MD format that describes how to obtain necessary credentials to connect to the Twitter API

**Comment by MANISH-LAB** [comment]
assign me this issue.

**Comment by atompie** [comment]
@MANISH-LAB Sorry this one is already assigned maby some of these issues interest you: 

* https://github.com/Tracardi/tracardi/issues/730
* https://github.com/Tracardi/tracardi/issues/731

These are very good tasks to start with.
