### ISSUE TITLE
Document Join string list plugin

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#741]
**Is your feature request related to a problem? Please describe.**
Please add documentation to Join string list plugin. 

![Screenshot from 2022-10-11 23-02-22](https://user-images.githubusercontent.com/16271564/195197838-b07aa29f-6963-4ddc-b78f-ba40aa9a9a1a.png)

The plugin works fine but needs documentation. To do it clone your tracardi-api fork and add file `string_join_action.md` in the tracardi-api project in the folder: docs/flow/actions and fill it with the simple documentation.

**Comment by yk-jp** [comment]
@atompie 
Hi, assign me this issue please.

**Comment by atompie** [comment]
This is example docs for the similar plugin (string splitter)

![Screenshot from 2022-10-11 23-15-32](https://user-images.githubusercontent.com/16271564/195199876-d5fc2ce7-c3b4-4dff-825e-cbde706e98ce.png)
