### ISSUE TITLE
Documentation for Sort Dictionary plugin

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#743]
**Is your feature request related to a problem? Please describe.**
Plugin has declared documentation `sorted_dict_action` but it is not filled. Please add it in the tracardi-api project in folder: `docs/flow/actions`. See the other files for documentation examples.

![Screenshot from 2022-10-12 21-27-39](https://user-images.githubusercontent.com/16271564/195431349-67803ffa-c660-4764-b5fb-53b041588e77.png)

**Comment by sameersecond** [comment]
Hey, can I work on this?

**Comment by atompie** [comment]
@sameersecond Assigned.

**Comment by atompie** [comment]
Done in 0.7.3
