### ISSUE TITLE
Plugin: Rate limit

### ISSUE THREAD

**Issue by bobsburgers** [Tracardi/tracardi#744]
**Is your feature request related to a problem? Please describe.**
I need to be able to do events only at a certain rate. Per profile, per resource.

**Describe the solution you'd like**
X # of times over Y time period. Like 1 every 30 seconds or 100 every day. 

**Describe alternatives you've considered**
Just doing a counter in redis with a timeout. or dumping to a db and query how many already done in timeframe.

**Comment by atompie** [comment]
The docs for the forthcoming plugin: 

https://github.com/Tracardi/tracardi-api/blob/master/docs/flow/actions/limiter_action.md
