### ISSUE TITLE
Base64 decoder plugin

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#749]
**Is your feature request related to a problem? Please describe.**
Plugin that decodes base64 string. This plugin is very simple in terms of python. The challenge is to add it as plugin to Tracardi. This is also very simple if you read this http://docs.tracardi.com/plugins/tutorial/part1/ and http://docs.tracardi.com/plugins/tutorial/part2

**Describe the solution you'd like**
User defines in plugin configuration what strings should be decoded. 

Example of configuration 

```json
{
   "value": "event@properties.some_value1"
}
```

Input:
Workflow payload

Output:
Decoded string

**Additional context**
You will need to setup the dev environment. Here is the tutorial how to do it. Also to understand how the plugins work please read http://docs.tracardi.com/plugins/tutorial/part1/ and http://docs.tracardi.com/plugins/tutorial/part2/ . The next part is o its way so you can extend your knowledge about Tracardi plugins.

**Comment by Ananya2003Gupta** [comment]
Can I work on this issue ?

**Comment by knittl** [comment]
I started work in progress for #750 and #749, I hope I'm on the right track: https://github.com/knittl/tracardi/commits/base64-actions

PR will follow later this evening or tomorrow :)

**Comment by atompie** [comment]
Sorry @Ananya2003Gupta this task is already assigned you you like me to find you something similar?

**Comment by atompie** [comment]
@knittl you are on the right track. Code looks good. :)

**Comment by Ananya2003Gupta** [comment]
Okay , no worries.
I am new to plugins, so maybe another good first issue.
