### ISSUE TITLE
Make a set of plug-ins for open ai

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#771]
**Is your feature request related to a problem? Please describe.**

Make a set of plug-ins for open ai API - https://beta.openai.com/docs/api-reference/models

**Comment by akashroy1** [comment]
I want to work on this. Can you please explain the exact functionality that needs to be added?

**Comment by atompie** [comment]
@akashroy1 Sorry This task was not closed when done. It is already done.
