### ISSUE TITLE
Plugin that makes string operations on data

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#80]
This plug-in is to make a string operations like:
* lowercase 
* remove spaces 
* split 
and other such as 

on a data defined by day notation in Tracardi￼

# Requirements 

Must use DotAccesor

# Input

Example:

{
"Profile@traits.private.poi.name": "removeSpaces",
"Profile@traits.private.poi.name":"trimSpaces",
"Profile@traits.private.poi.age":"makeInt"
}

Possible list of operations:

* makeFloat
* uppercase
* lowercase
* uppercaseFirstLetter
* splitBySpace

**Comment by patromi** [comment]
@atompie https://github.com/patromi/tracardi-string-operations
