### ISSUE TITLE
Plugin that strips string from some charaters

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#804]
**Problem Description:**
Create a Tracardi plugin that strips string from some charaters.

**Prerequisites to Meet:**

- Fork the repository and work exclusively on the 0.8.2-dev branch. Only changes made in this branch will be accepted.

**Steps to Create the Plugin in Tracardi:**

1. **Review Tracardi Plugin Documentation:**
   - Start by conducting a comprehensive review of the Tracardi plugin documentation, which can be found at http://docs.tracardi.com/plugins/.

2. **Set Up Development Environment:**
   - Follow the instructions outlined in the documentation located at http://docs.tracardi.com/development/python_env/ in order to establish an appropriate development environment for your plugin creation.

3. **Implement String Replacement Functionality:**
   - Develop the plugin to perform string replacement within data payloads as per your requirements. Ensure that it can be easily configured to replace specific strings with desired replacements.

4. **Testing and Validation:**
   - Thoroughly test the plugin to ensure its correctness and effectiveness in replacing strings within payloads. Verify that it operates as expected.

5. **Documentation and Usage Instructions:**
   - Prepare clear and concise documentation that explains how to use the newly created plugin. Include details on configuration options, input parameters, and expected outcomes.

6. **Share Progress on Social Media (Optional):**
   - If possible, share your progress and achievements related to the development of the plugin on social media platforms or within the Tracardi community to encourage collaboration and awareness.

By following these steps, you will successfully create a Tracardi plugin that can replace specified strings within data payloads, contributing to the functionality and flexibility of Tracardi's data processing capabilities.

**Comment by ojninja16** [comment]
Hi @atompie ..... I would like to work on it .....thanks

**Comment by atompie** [comment]
Sure go ahead.

**Comment by atompie** [comment]
This task is available for HACKTOBERFEST 2023

**Comment by ghost** [comment]
Hi @atompie , I would love to take a shot at this

**Comment by atompie** [comment]
@kokobhara sure assigned.

**Comment by atompie** [comment]
@kokobhara please take a look at http://docs.tracardi.com/plugins/tutorial/part1/ where we described how to write plugins.

**Comment by akashroy1** [comment]
I want to work on this issue.

**Comment by atompie** [comment]
@akashroy1 sorry I found you another one. The plugins are all the same just a little different logic. https://github.com/Tracardi/tracardi/issues/765. Please comment on this one and I will assign you.

**Comment by ghost** [comment]
@atompie , can you elaborate more on the requirement: strips string from some charaters. In the description above, it's mentioned for string replacement. An example or two should suffice. Thanks!

**Comment by atompie** [comment]
@kokobhara  Sure. If we have string with @ then all @ should be removed. We can define several chars to remove for example "6)a" then all the chars from that string should be removed.

**Comment by ghost** [comment]
This makes it clearer. Thanks!

**Comment by ghost** [comment]
I'm almost done implementing the functionality for the plugin. But I'm not sure as to how to go about testing it. The docs mentioned spinning up a separate API server, and then attaching this to that project through PyCharm. Unfortunately, I use VS code for my work, and cannot use PyCharm at the moment. Is there anything I can do to solve this?

**Comment by atompie** [comment]
@kokobhara Hi Good start would be to create a unit test. We have some helper functions to do it. You could check some examples in https://github.com/Tracardi/tracardi/blob/master/test/unit/plugins/.

Here is one good example: https://github.com/Tracardi/tracardi/blob/master/test/unit/plugins/test_plugin_if.py

**Comment by atompie** [comment]
@kokobhara As to testing it in the GUI it is a bit more complicated. You do not have to do it we can test it for you. 

If you would like to give it a try. 

You'll need 2 projects. One is tracardi/tracardi-api and another is tracardi/tracardi. tracardi-api depends on tracardi so you will have to modify $PYTHONPATH to reference tracardi as a module (Maybe this will help: https://code.visualstudio.com/docs/python/environments#_use-of-the-pythonpath-variable). 

 Tracardi API will need  elastic search and redis. Here is how to start them:

http://docs.tracardi.com/installation/dependencies/

When you have the required dependencies running then you should be able to stare tracardi-api.

When the API is running run docker with GUI. 

```
docker run -p 8787:80 tracardi/tracardi-gui
```

It will be available at localhost:8787. When asked for Tracardi API type http://localhost:8686.

Your plugin should be available in the Automation part of the system.

**Comment by ghost** [comment]
Hi @atompie , I've opened a PR #827 , I've added a unit test to test the plugin. What I'm not sure is the Metadata for the plugin, I've cobbled up whatever I could from the documentation and from other plugins. Let me know in case of any changes. Thanks!
