### ISSUE TITLE
Fix typos and enhance communication in README.md and Contributing.md

### ISSUE THREAD

**Issue by Agnik7** [Tracardi/tracardi#822]
Describe the bug
------------------------

There are a lot of grammatical mistakes, commonly known as typos in most places. Additionally, some of the texts or phrases can be improved for better communication.

To Reproduce
------------------------

1. Go to [tracardi](https://github.com/Tracardi/tracardi)
2. Scroll down to `README.md`.
4. Open the `CONTRIBUTING.md` as well.
5. The grammatical errors are visible.

Expected behavior
----------------------------

The sentences should be devoid of any error and aid in better communication.

Screenshots
----------------------------

![tempsnip](https://github.com/Tracardi/tracardi/assets/77234005/030c7a6d-4c1f-40cc-b356-02108ffbf00e)

**Note: This screenshot is just an example of the inconsistencies. There are other similar inconsistencies as well.**

**Comment by Agnik7** [comment]
Requesting the maintainers to kindly assign this issue to me as part of Hacktoberfest. Apologies for any inconvenience caused.

**Comment by atompie** [comment]
Hello @Agnik7 could you please make changes in our current dev branch that is 0.8.1-dev. Thanks

**Comment by Agnik7** [comment]
@atompie Sure!! I am working on it!!

**Comment by Agnik7** [comment]
@atompie I have created a PR #823 . Requesting your review. Thank you!!

**Comment by atompie** [comment]
The PR accepted good work :)
