### ISSUE TITLE
Add documentation for string stripper. 

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#828]
**Is your feature request related to a problem? Please describe.**
String stripper is missing documentation

**Describe the solution you'd like**
Create a MD file with documentation. See other documentations eg.  https://github.com/Tracardi/tracardi-api/blob/0.8.2-dev/docs/flow/actions/contains_pattern_action.md

Documentation should be added to tracardi/tracardi-api repo. 
![Screenshot from 2023-10-10 08-56-07](https://github.com/Tracardi/tracardi/assets/16271564/a4bd7342-80ce-479c-9418-df3c6a1cee42)

**Comment by Tejoooo** [comment]
@atompie can u assign me this

**Comment by ghost** [comment]
Hi @atompie , I'll take this up. Sorry I missed your comment on the original issue.

**Comment by atompie** [comment]
Hi @Tejoooo if you are looking for similar documentation task we have a lot of undocumented plugins that waits for anyone that would like to document them. Please see https://github.com/Tracardi/tracardi/issues/830

**Comment by ghost** [comment]
@atompie , I have raised a PR in the tracardi-api repo.

**Comment by ghost** [comment]
The PR is merged. This can be closed. Thanks!
