### ISSUE TITLE
Create a timedelta plugin

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#840]
Task: Create a Tracardi Plugin that creates a date based on time delta, now + delta

Problem Description:
Write a Tracardi plugin to address the need for a plugin that returns the date bases on time delta. 
Date must be computed using the time delta that is delivered by the user in the plugin form And this is the only configuration that the user must deliver. 
Current time is added to a defined delta and the date is returned on the result port. If there is an error it is returned on error port.

Prerequisites that must be meet

    Fork repository and work on the 0.8.2-dev branch. We will only accept changes in this branch.

Steps to Create the Plugin in Tracardi:

    Review Tracardi Plugin Documentation:
        Begin by thoroughly reviewing the Tracardi plugin documentation available at http://docs.tracardi.com/plugins/.

    Set Up Development Environment:
        Follow the instructions provided in the documentation at http://docs.tracardi.com/development/python_env/ to create a suitable development environment for plugin development.

**Comment by atompie** [comment]
This may help to speed up the development: https://www.youtube.com/watch?v=R_kr9mBAKAU

**Comment by ghost** [comment]
Hi @atompie , I'll take this up.
