### ISSUE TITLE
Unable to edit event source active status

### ISSUE THREAD

**Issue by si88har1h** [Tracardi/tracardi#856]
Describe the bug
------------------------
After an event source is created, I am not able to disable it to stop data from flowing into the dashboard. 
I click on Edit > Event source access
and i disable and save it. Still it reflects as active

To Reproduce
------------------------

1. Go to Inbound Traffic
2. Click on Add source
3. Add a source by adding required details
4. Click on the created source and click Edit
5. Scroll down to Event source access and disable it
6. click Save

Expected behavior
----------------------------
The event source is expected to be disabled after following the aforementioned steps. 

Screenshots
----------------------------
![image](https://github.com/Tracardi/tracardi/assets/55554315/fd70b68a-0908-44f3-a5cb-c52f1cd296ea)
![image](https://github.com/Tracardi/tracardi/assets/55554315/fb0cfd1c-2a2e-4c77-8651-c3ec334e3e47)
![image](https://github.com/Tracardi/tracardi/assets/55554315/2a110dff-d388-4c82-92ff-6188a316cd70)

Desktop (please complete the following information):
---------------------------------------------------------------------
 - OS: Ubuntu
 - Browser Chrome
 - Tracardi Version [e.g. 0.8.2]

Additional context
--------------------------

**Comment by atompie** [comment]
Fixed in 0.9.0-dev
