### ISSUE TITLE
Group and rank interests to segments plugin activity

### ISSUE THREAD

**Issue by mattcam** [Tracardi/tracardi#859]
Describe the solution you'd like
As a digital marketer, I would like to be able to map many interests to a few segments on a Tracardi profile record so that cohorts of similar profiles can be more easily targeted.

Describe alternatives you've considered

1. Other way that I could see to solve this within Tracardi was to build a very complex automation with many if statements. The issue with this approach is that it would be difficult to maintain for a scenario where there are many hundreds of interests that change frequently.
2. Another option would be for a more general plugin that allows for functional programming (e.g., JavaScript underscore). The issue with this approach is that it would be a big undertaking that would not be justified for the use case.

**Comment by atompie** [comment]
Merged
