### ISSUE TITLE
Plugin that integrates with AirTable

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#89]
# Documentation

https://towardsdatascience.com/downloading-airtable-data-into-python-89e5c7107a24

**Comment by emge1** [comment]
.

**Comment by atompie** [comment]
@emge1 What is the status of this task.

**Comment by emge1** [comment]
@atompie Hi, I think the plugin is done. Here is the repository: https://github.com/emge1/tracardi-airtable-integrator. The manual test was passed.
I am only thinking about adding some pictures to README.md to make it easier to learn. And I'll probably change the examples in convention of Tracardi docs
