### ISSUE TITLE
Plugin that publishes payload to AWS SQS

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#95]
Resources:

* [https://www.learnaws.org/2020/12/17/aws-sqs-boto3-guide/](https://www.learnaws.org/2020/12/17/aws-sqs-boto3-guide/)

**Comment by bartdob** [comment]
This issue is free or You will do it?

**Comment by atompie** [comment]
> This issue is free or You will do it?

@bartdob it is free
